// 차트 가이드 — 전체 지표 카탈로그. 스크린샷에 나온 4개 카테고리(차트유형/
// 오버레이/보조지표/기타지표) 체계를 그대로 따라간다. 정확도가 불확실한
// 극히 일부 지표(AB Ratio, NCO, RCI, RMI 등 한국 HTS 고유 산식이 표준화되어
// 있지 않은 것들, 역시계곡선처럼 계산이 매우 복잡한 것)는 잘못된 정보를
// 주는 것보다 낫다고 판단해 이번 배치에서 제외했다.

export const CATEGORIES = [
  { id: "chartform", label: "차트유형" },
  { id: "overlay", label: "오버레이" },
  { id: "oscillator", label: "보조지표" },
  { id: "other", label: "기타지표" },
];

export const INDICATORS = [
  {
    id: "timeframe",
    category: "chartform",
    name: "봉 주기 (일봉/주봉)",
    eng: "Timeframe",
    summary: "같은 가격 데이터를 며칠씩 묶느냐에 따라 캔들 하나가 나타내는 기간이 달라져요",
    detail:
      "캔들 하나가 하루를 나타내면 일봉, 일주일을 나타내면 주봉, 한 달이면 월봉이에요. 아래 위 두 차트는 완전히 같은 24일치 데이터인데, 위는 하루씩(일봉), 아래는 4일씩 묶어서(주봉 느낌) 그린 거예요.",
    tip: "짧은 주기(일봉·분봉)는 세부 움직임을 놓치지 않지만 잔파동이 많고, 긴 주기(주봉·월봉)는 큰 흐름을 보기 편하지만 세부 타이밍은 안 보여요.",
    visual: { type: "timeframe-compare" },
  },
  // ---- 차트유형 ----
  {
    id: "candle",
    category: "chartform",
    name: "캔들차트",
    eng: "Candlestick",
    summary: "시가·고가·저가·종가 4가지 가격을 몸통과 꼬리로 표현하는 가장 기본적인 차트",
    detail:
      "몸통은 시가와 종가 사이 구간, 위아래 꼬리는 그날의 고가·저가를 나타내요. 한국 시장에서는 종가가 시가보다 높으면 빨간색(양봉), 낮으면 파란색(음봉)으로 표시해요.",
    tip: "몸통이 길수록 그 기간 동안 힘있게 움직였다는 뜻이고, 꼬리가 길면 한쪽으로 밀렸다가 다시 되돌아왔다는 뜻이에요.",
    visual: { type: "chartform", form: "candle" },
  },
  {
    id: "line",
    category: "chartform",
    name: "라인차트",
    eng: "Line",
    summary: "종가만 이어서 그린 가장 단순한 차트",
    detail: "각 기간의 종가만 점으로 찍고 선으로 연결해요. 세부 변동은 안 보이지만 전체 추세를 한눈에 파악하기 좋아요.",
    tip: "여러 종목의 장기 추세를 겹쳐서 비교할 때 특히 유용해요.",
    visual: { type: "chartform", form: "line" },
  },
  {
    id: "area",
    category: "chartform",
    name: "영역라인",
    eng: "Area",
    summary: "라인차트 아래를 색으로 채워 추세를 더 강조한 형태",
    detail: "기본 구조는 라인차트와 같고, 선 아래 영역을 채색해서 상승·하락의 크기를 시각적으로 더 도드라지게 보여줘요.",
    tip: "여러 종목을 겹쳐 그릴 땐 오히려 라인차트가 더 보기 편할 수 있어요 — 영역라인은 단일 종목 볼 때 강점이 있어요.",
    visual: { type: "chartform", form: "area" },
  },
  {
    id: "bar",
    category: "chartform",
    name: "바차트",
    eng: "OHLC Bar",
    summary: "캔들의 몸통 없이 시가·고가·저가·종가를 선으로만 표시",
    detail: "세로선이 고가~저가 범위, 왼쪽 짧은 가지가 시가, 오른쪽 짧은 가지가 종가예요. 캔들과 정보량은 같지만 더 가늘게 표시돼요.",
    tip: "여러 지표를 겹쳐 볼 때 캔들 몸통이 다른 선을 가리는 게 싫다면 바차트가 더 깔끔해요.",
    visual: { type: "chartform", form: "bar" },
  },
  {
    id: "heikin",
    category: "chartform",
    name: "Heikin-Ashi",
    eng: "Heikin-Ashi",
    summary: "직전 캔들 값을 평균내어 추세를 매끄럽게 보여주는 변형 캔들",
    detail: "일반 캔들과 계산식이 달라서(직전 시가·종가 평균 등) 잔파동이 줄어들고 추세가 지속되는 구간이 색으로 뭉쳐서 보여요.",
    tip: "같은 색 캔들이 연속되면 추세가 강하다는 뜻이고, 몸통이 거의 없는 캔들이 나오면 힘이 빠지고 있다는 신호로 봐요.",
    visual: { type: "chartform", form: "heikin" },
  },

  // ---- 오버레이 ----
  {
    id: "sma",
    category: "overlay",
    name: "이동평균선",
    eng: "Moving Average (MA)",
    summary: "최근 N일 종가의 평균을 이어 그린, 가장 널리 쓰이는 추세선",
    detail: "가격의 잔물결을 지우고 큰 흐름만 보여줘요. 여러 기간(5일선, 20일선, 60일선 등)을 같이 놓고 배열을 보는 게 일반적이에요.",
    tip: "가격이 이동평균선 위에 있으면 상승 추세, 아래 있으면 하락 추세로 해석하는 게 기본이에요.",
    visual: { type: "overlay-line", period: 6 },
  },
  {
    id: "bollinger",
    category: "overlay",
    name: "Bollinger Band",
    eng: "Bollinger Band",
    summary: "이동평균선 위아래로 변동성만큼 밴드를 그린 지표",
    detail: "가격 변동이 커지면 밴드 폭이 넓어지고, 잠잠해지면 좁아져요. 통계적으로 가격은 대부분 이 밴드 안에서 움직여요.",
    tip: "밴드가 좁아졌다가(스퀴즈) 한쪽으로 급하게 벌어지면, 큰 방향성 움직임이 막 시작됐다는 신호로 자주 해석돼요.",
    visual: { type: "overlay-band" },
  },
  {
    id: "ichimoku",
    category: "overlay",
    name: "일목균형표",
    eng: "Ichimoku Cloud",
    summary: "여러 개의 평균선으로 구름(지지·저항대)을 만들어 추세와 균형을 함께 보는 지표",
    detail: "일본에서 개발된 지표로, 여러 선이 겹쳐서 만드는 구름대가 지지선·저항선 역할을 해요. 여기선 핵심 두 선만 단순화해서 보여드려요.",
    tip: "가격이 구름 위에 있으면 상승 우위, 구름 아래 있으면 하락 우위로 해석하는 게 기본 틀이에요.",
    visual: { type: "overlay-cloud" },
  },
  {
    id: "sar",
    category: "overlay",
    name: "Parabolic SAR",
    eng: "Parabolic SAR",
    summary: "가격 위아래로 점을 찍어 추세 전환 시점을 표시하는 지표",
    detail: "점이 가격 아래 있으면 상승 추세, 위로 '점프'해서 옮겨가면 하락 추세로 전환됐다는 신호예요.",
    tip: "점이 자주 뒤집히면(휩소) 추세가 뚜렷하지 않은 횡보장이라는 뜻이니 주의가 필요해요.",
    visual: { type: "overlay-dots" },
  },
  {
    id: "demand-zone",
    category: "overlay",
    name: "매물대",
    eng: "Volume Profile / Demand Zone",
    summary: "특정 가격대에서 얼마나 많은 거래가 쌓였는지 옆으로 표시하는 지표",
    detail: "거래가 많이 몰렸던 가격대는 그만큼 많은 사람이 사고판 '기억'이 남아있는 구간이라, 나중에 그 가격에 다시 오면 지지·저항으로 작용하는 경우가 많아요.",
    tip: "매물대가 두꺼운 구간을 뚫고 올라가면 그 위는 저항이 약해졌다고 보고, 반대로 못 뚫으면 저항대로 작용했다고 해석해요.",
    visual: { type: "overlay-zone" },
  },

  // ---- 보조지표 ----
  {
    id: "volume",
    category: "oscillator",
    name: "거래량",
    eng: "Volume",
    summary: "그 기간 동안 실제로 얼마나 많은 주식이 거래됐는지 보여주는 막대그래프",
    detail: "가격 아래에 막대로 표시되며, 캔들 색과 맞춰서 상승일엔 빨간, 하락일엔 파란 막대로 표시되는 경우가 많아요.",
    tip: "가격이 크게 움직였는데 거래량이 평소보다 훨씬 많다면, 그 움직임의 신뢰도가 더 높다고 보는 게 일반적이에요.",
    visual: { type: "pane-bars" },
  },
  {
    id: "rsi",
    category: "oscillator",
    name: "RSI",
    eng: "Relative Strength Index",
    summary: "최근 상승폭과 하락폭의 비율로 과열·침체 정도를 0~100 사이 숫자로 보여주는 지표",
    detail: "70 이상이면 과매수(너무 많이 올랐다), 30 이하면 과매도(너무 많이 빠졌다) 구간으로 흔히 해석해요.",
    tip: "가격은 신고가를 갱신하는데 RSI는 그만큼 안 오르는 '다이버전스'가 나오면, 추세 전환의 초기 신호로 자주 언급돼요.",
    visual: { type: "pane-oscillator", calc: "rsi", bands: [30, 70] },
  },
  {
    id: "stochastic",
    category: "oscillator",
    name: "스토캐스틱",
    eng: "Stochastic",
    summary: "최근 일정 기간의 고가·저가 범위 안에서 현재 가격의 위치를 0~100으로 표시",
    detail: "80 이상은 그 기간 범위의 최상단 근처(과매수), 20 이하는 최하단 근처(과매도)로 흔히 해석해요.",
    tip: "RSI보다 반응이 더 빨라서(민감해서) 짧은 구간 매매 참고용으로 많이 쓰이지만, 그만큼 신호도 자주 나와요.",
    visual: { type: "pane-oscillator", calc: "stochastic", bands: [20, 80] },
  },
  {
    id: "macd",
    category: "oscillator",
    name: "MACD",
    eng: "Moving Average Convergence Divergence",
    summary: "단기·장기 이동평균선의 차이를 이용해 추세의 방향과 힘을 보는 지표",
    detail: "MACD선(주황)이 시그널선(파랑)을 위로 뚫으면 매수 신호, 아래로 뚫으면 매도 신호로 흔히 해석해요. 막대(히스토그램)는 두 선의 차이 크기예요.",
    tip: "히스토그램 막대가 점점 짧아지고 있다면, 지금 추세의 힘이 빠지고 있다는 신호로 종종 해석돼요.",
    visual: { type: "pane-macd" },
  },
  {
    id: "obv",
    category: "oscillator",
    name: "OBV",
    eng: "On Balance Volume",
    summary: "가격이 오른 날엔 거래량을 더하고 내린 날엔 빼서, 거래량의 누적 흐름을 선으로 표시",
    detail: "가격보다 거래량(수급)의 큰 흐름을 먼저 보여주는 지표예요. 가격은 아직 안 움직였는데 OBV가 먼저 방향을 잡는 경우가 있어요.",
    tip: "가격은 옆으로 횡보하는데 OBV가 꾸준히 오른다면, 조용히 매집이 진행되고 있다는 신호로 해석되기도 해요.",
    visual: { type: "pane-line", calc: "obv" },
  },
  {
    id: "disparity",
    category: "oscillator",
    name: "이격도",
    eng: "Disparity",
    summary: "현재 가격이 이동평균선에서 몇 % 떨어져 있는지 보여주는 지표",
    detail: "100이면 가격이 이동평균선과 정확히 같다는 뜻이에요. 100보다 많이 높으면 평균보다 너무 많이 올랐다는 뜻이고, 많이 낮으면 너무 많이 빠졌다는 뜻이에요.",
    tip: "이격도가 극단적으로 벌어지면, 평균 쪽으로 되돌아오려는 힘(평균 회귀)이 작용할 가능성이 있다고 보는 시각이 있어요.",
    visual: { type: "pane-oscillator-center" },
  },

  // ==================== 2차 배치 ====================

  // ---- 차트유형 (나머지) ----
  {
    id: "renko",
    category: "chartform",
    name: "렌코",
    eng: "Renko",
    summary: "시간 축을 무시하고, 가격이 일정 크기만큼 움직일 때마다 벽돌(box) 하나씩 쌓는 차트",
    detail: "일반 캔들은 '하루마다' 캔들이 하나 생기지만, 렌코는 '가격이 정해진 크기만큼 움직여야만' 벽돌이 하나 생겨요. 그래서 작은 등락(노이즈)이 전부 사라지고 진짜 추세만 남아요.",
    tip: "벽돌 색이 계속 같은 방향으로 이어지면 추세가 살아있다는 뜻이고, 색이 자주 바뀌면 방향성이 없는 구간이에요.",
    visual: { type: "chartform", form: "renko" },
  },
  {
    id: "pnf",
    category: "chartform",
    name: "PnF (포인트 앤 피겨)",
    eng: "Point and Figure",
    summary: "오르는 구간은 X, 내리는 구간은 O로, 시간 축 없이 가격 움직임만 표시하는 차트",
    detail: "렌코처럼 일정 크기(box) 단위로 움직임을 걸러내되, 방향이 바뀔 때만 새 칸(열)으로 넘어가요. X 칸이 길게 이어지면 강한 상승, O 칸이 길면 강한 하락이에요.",
    tip: "칸(열)이 자주 안 바뀌고 한쪽으로 길게 이어질수록, 그 추세가 강하고 오래 지속되고 있다는 뜻이에요.",
    visual: { type: "chartform", form: "pnf" },
  },
  {
    id: "threeline",
    category: "chartform",
    name: "삼선전환도",
    eng: "Three Line Break",
    summary: "렌코와 비슷하지만, 직전 3개 선의 범위를 완전히 뚫어야만 방향이 바뀌는 차트",
    detail: "렌코보다 방향 전환 기준이 훨씬 까다로워요. 그만큼 잔파동에 덜 흔들리고, 진짜 큰 추세 전환만 잡아내는 데 특화되어 있어요.",
    tip: "선이 방향을 바꾸는 순간은, 최근 3개 구간 전체를 뒤집을 만큼 강한 반전이 나왔다는 뜻이라 신뢰도가 비교적 높게 여겨져요.",
    visual: { type: "chartform", form: "threeline" },
  },
  {
    id: "kagi",
    category: "chartform",
    name: "Kagi",
    eng: "Kagi",
    summary: "하나로 이어진 지그재그 선 — 추세가 꺾이는 지점에서만 방향이 바뀌는 차트",
    detail: "가격이 일정 폭(반전 기준) 이상 되돌려야만 선의 방향이 바뀌어요. 직전 고점·저점을 돌파하면 선이 굵어지고, 못 넘으면 가늘게 유지돼요.",
    tip: "선이 굵어지는 순간(직전 고점 돌파)은 매수 신호, 가늘어지는 순간(직전 저점 이탈)은 매도 신호로 흔히 해석해요.",
    visual: { type: "chartform", form: "kagi" },
  },
  {
    id: "swing",
    category: "chartform",
    name: "스윙 (지그재그)",
    eng: "Swing / Zigzag",
    summary: "의미 있는 고점과 저점만 남기고 나머지는 다 걸러낸 뒤 직선으로 연결한 차트",
    detail: "일정 크기 이상 움직인 진짜 '고점'과 '저점'만 골라서 점을 찍고 이어요. 파동의 큰 흐름(어디서 올랐고 어디서 빠졌는지)을 한눈에 파악하기 좋아요.",
    tip: "실제 매매 신호로 쓰기보다는, 지난 흐름에서 중요했던 전환점들을 복기하고 눈으로 확인하는 용도로 많이 써요.",
    visual: { type: "chartform", form: "swing" },
  },

  // ---- 오버레이 (나머지) ----
  {
    id: "envelope",
    category: "overlay",
    name: "Envelope",
    eng: "Envelope",
    summary: "이동평균선 위아래로 정해진 비율(%)만큼 띄운 밴드",
    detail: "볼린저밴드가 변동성(통계)에 따라 밴드 폭이 자동으로 바뀌는 반면, Envelope는 항상 고정된 비율(예: ±6%)로 밴드를 그려요. 계산이 단순해서 초창기부터 쓰이던 방식이에요.",
    tip: "가격이 위쪽 밴드에 닿으면 과매수, 아래쪽 밴드에 닿으면 과매도로 보는 게 기본적인 활용법이에요.",
    visual: { type: "overlay-band", calc: "envelope" },
  },
  {
    id: "donchian",
    category: "overlay",
    name: "Price Channel",
    eng: "Donchian Channel",
    summary: "최근 N일 중 가장 높았던 고가와 가장 낮았던 저가로 그린 채널",
    detail: "계산 방식이 아주 단순해요 — 그냥 최근 N일의 최고가·최저가를 그대로 선으로 그려요. 유명한 추세추종 매매 기법(터틀 트레이딩)에서 핵심적으로 쓰인 지표예요.",
    tip: "가격이 채널 상단을 새로 뚫으면 신고가 돌파(매수 신호), 하단을 뚫으면 신저가 이탈(매도 신호)로 흔히 활용돼요.",
    visual: { type: "overlay-band", calc: "donchian" },
  },
  {
    id: "supertrend",
    category: "overlay",
    name: "Super Trend",
    eng: "SuperTrend",
    summary: "변동성을 반영해 가격을 따라다니다가, 추세가 바뀌면 반대편으로 점프하는 추세선",
    detail: "가격 움직임의 변동폭(ATR)을 기준으로 상승 추세일 땐 가격 아래에, 하락 추세일 땐 가격 위에 선이 그려져요. 추세가 꺾이면 선이 반대편으로 넘어가면서 색도 바뀌어요.",
    tip: "선이 가격 아래(빨강)에서 위(파랑)로 넘어가는 순간이 추세 전환 신호로 흔히 해석돼요. 한눈에 보기 쉬워서 초보자들도 많이 참고해요.",
    visual: { type: "overlay-trail" },
  },
  {
    id: "pivot",
    category: "overlay",
    name: "Pivot",
    eng: "Pivot Points",
    summary: "직전 기간의 고가·저가·종가로 계산한 지지선·저항선을 오늘 미리 그어두는 지표",
    detail: "전날(또는 전 기간)의 가격 데이터만으로 오늘의 예상 지지·저항 라인을 계산해요. 별도 설정 없이도 계산식이 고정돼 있어서 데이 트레이더들이 특히 많이 참고해요.",
    tip: "가격이 R1(저항) 근처에서 막히는지, S1(지지) 근처에서 반등하는지를 보면서 매매 타이밍을 잡는 데 활용돼요.",
    visual: { type: "overlay-hlines" },
  },
  {
    id: "demark",
    category: "overlay",
    name: "Demark",
    eng: "Demark Pivot",
    summary: "일반 Pivot과 계산식이 다른, 톰 디마크가 고안한 지지·저항 계산법",
    detail: "직전 캔들이 양봉이었는지 음봉이었는지에 따라 가중치를 다르게 줘서 지지·저항을 계산해요. 그래서 일반 Pivot보다 그날그날의 캔들 방향을 더 민감하게 반영해요.",
    tip: "일반 Pivot과 Demark Pivot 값을 같이 놓고 비교해보면, 두 계산법이 얼마나 비슷하거나 다른 레벨을 제시하는지 확인할 수 있어요.",
    visual: { type: "overlay-hlines", calc: "demark" },
  },
  {
    id: "netchart",
    category: "overlay",
    name: "그물차트",
    eng: "Net Chart",
    summary: "여러 굵기의 이동평균선을 겹쳐서, 그물처럼 촘촘한 지지·저항대를 시각화한 지표",
    detail: "이 데모에서는 이해를 돕기 위해 Envelope 밴드로 단순화해서 보여드려요. 실제로는 여러 기간의 이동평균선을 동시에 겹쳐 그려서, 그 선들이 몰려있는 구간을 강한 지지·저항대로 해석해요.",
    tip: "여러 선이 한곳에 몰려있을수록(수렴) 그 가격대의 지지·저항 힘이 강하다고 보고, 선들이 넓게 퍼져있으면(발산) 추세가 강하게 진행 중이라고 봐요.",
    visual: { type: "overlay-band", calc: "envelope" },
  },

  // ---- 보조지표 (나머지) ----
  {
    id: "volumeSma",
    category: "oscillator",
    name: "거래량이동평균",
    eng: "Volume MA",
    summary: "거래량 자체의 평균선 — 오늘 거래량이 평소보다 많은지 적은지 비교하는 기준선",
    detail: "거래량 막대 위에 평균선을 하나 그어서, '오늘 거래량이 평소(평균) 대비 많은 편인지 적은 편인지'를 한눈에 비교할 수 있게 해줘요.",
    tip: "거래량 막대가 평균선을 크게 뚫고 올라오는 날은, 그날의 가격 움직임에 힘이 실려 있다는 신호로 흔히 해석해요.",
    visual: { type: "pane-bars-avg" },
  },
  {
    id: "psych",
    category: "oscillator",
    name: "심리도",
    eng: "Psychological Line",
    summary: "최근 N일 중 상승 마감한 날의 비율을 %로 보여주는 지표",
    detail: "예를 들어 최근 10일 중 7일이 올랐다면 심리도는 70이에요. 시장 참여자들의 '오르는 날이 많았나, 내리는 날이 많았나'하는 심리를 숫자로 표현한 거예요.",
    tip: "너무 높으면(과열) 곧 쉬어갈 가능성, 너무 낮으면(침체) 곧 반등할 가능성을 시사한다고 흔히 해석해요.",
    visual: { type: "pane-oscillator", calc: "psych", bands: [25, 75] },
  },
  {
    id: "psych2",
    category: "oscillator",
    name: "신심리도",
    eng: "New Psychological Line",
    summary: "심리도보다 더 짧은 기간으로 계산해서, 반응이 더 빠르고 민감한 버전",
    detail: "계산 방식은 심리도와 똑같은데, 살펴보는 기간을 더 짧게 잡아요. 그만큼 최근 며칠의 분위기 변화에 더 빠르게 반응해요.",
    tip: "심리도(느린 반응)와 신심리도(빠른 반응)를 같이 놓고 보면서, 둘의 방향이 같은지 다른지로 신뢰도를 가늠하기도 해요.",
    visual: { type: "pane-oscillator", calc: "psych", bands: [20, 80] },
  },
  {
    id: "adx",
    category: "oscillator",
    name: "ADX",
    eng: "Average Directional Index",
    summary: "가격이 오르는지 내리는지가 아니라, '추세가 얼마나 강한지'만 0~100으로 보여주는 지표",
    detail: "방향은 알려주지 않고 오직 힘(강도)만 알려주는 게 특징이에요. 값이 높으면 상승이든 하락이든 추세가 뚜렷하다는 뜻이고, 낮으면 방향 없이 횡보하고 있다는 뜻이에요.",
    tip: "ADX가 낮은 구간(횡보장)에서는 추세추종형 지표(이동평균선 등)보다 오실레이터형 지표(RSI 등)가 더 잘 맞는다고 흔히 얘기해요.",
    visual: { type: "pane-oscillator", calc: "adx", bands: [20, 40] },
  },
  {
    id: "cci",
    category: "oscillator",
    name: "CCI",
    eng: "Commodity Channel Index",
    summary: "가격이 자기 평균에서 얼마나 멀리 떨어져 있는지를 표준화해서 보여주는 지표",
    detail: "0을 기준으로 위아래로 움직이며, 보통 +100과 −100을 과매수·과매도 기준선으로 삼아요. 원래 원자재(상품) 시장을 위해 만들어졌지만 주식에도 널리 쓰여요.",
    tip: "+100을 강하게 뚫고 올라가는 구간은 강한 상승 추세의 시작으로, −100을 뚫고 내려가는 구간은 강한 하락의 시작으로 해석되기도 해요.",
    visual: { type: "pane-oscillator-center", calc: "cci" },
  },
  {
    id: "williamsr",
    category: "oscillator",
    name: "Williams %R",
    eng: "Williams %R",
    summary: "스토캐스틱과 같은 원리인데, −100~0 사이 숫자로 뒤집어서 보여주는 지표",
    detail: "계산 원리는 스토캐스틱과 거의 같아요. 다만 표시 방식만 달라서, 0에 가까울수록 과매수, −100에 가까울수록 과매도예요.",
    tip: "−20 위쪽은 과매수, −80 아래쪽은 과매도 구간으로 흔히 해석해요. 스토캐스틱을 이미 쓰고 있다면 굳이 같이 쓸 필요는 없어요.",
    visual: { type: "pane-oscillator", calc: "williams", bands: [-80, -20] },
  },
  {
    id: "momentum",
    category: "oscillator",
    name: "Momentum",
    eng: "Momentum",
    summary: "오늘 가격에서 N일 전 가격을 그냥 빼기만 한, 가장 단순한 추세 강도 지표",
    detail: "복잡한 계산 없이 '지금 가격 − N일 전 가격'만 계산해요. 0보다 위면 N일 전보다 올랐다는 뜻, 아래면 내렸다는 뜻이에요.",
    tip: "값 자체보다는 '방향이 꺾이는 시점'을 보는 데 많이 써요 — 계속 오르던 모멘텀이 꺾이기 시작하면 상승 힘이 빠지고 있다는 신호예요.",
    visual: { type: "pane-oscillator-center", calc: "momentum" },
  },
  {
    id: "roc",
    category: "oscillator",
    name: "ROC",
    eng: "Rate of Change",
    summary: "Momentum과 똑같은 개념인데, 차이를 %(비율)로 표시하는 지표",
    detail: "'지금 가격이 N일 전보다 몇 % 올랐나(내렸나)'를 그대로 보여줘요. Momentum은 절대값(원)으로, ROC는 %로 본다는 차이만 있어요.",
    tip: "종목마다 가격 단위가 다 달라서, 여러 종목을 비교할 땐 절대값인 Momentum보다 %인 ROC가 비교하기 더 편해요.",
    visual: { type: "pane-oscillator-center", calc: "roc" },
  },
  {
    id: "pvt",
    category: "oscillator",
    name: "PVT",
    eng: "Price Volume Trend",
    summary: "OBV와 비슷한데, 거래량을 통째로 더하지 않고 '가격 변동률만큼만' 반영하는 지표",
    detail: "OBV는 오른 날 거래량을 통째로 더하지만, PVT는 '몇 % 올랐는지'에 비례해서 거래량을 일부만 반영해요. 그래서 작은 변동엔 덜 민감하게 반응해요.",
    tip: "OBV랑 같이 놓고 보면서, 두 지표의 흐름이 비슷한지 확인하면 수급 방향에 대한 신뢰도를 더 높일 수 있어요.",
    visual: { type: "pane-line", calc: "pvt" },
  },
  {
    id: "adline",
    category: "oscillator",
    name: "AD Line",
    eng: "Accumulation/Distribution Line",
    summary: "그날 종가가 고가·저가 범위의 어디쯤에서 마감했는지를 반영한 누적 수급 지표",
    detail: "단순히 올랐는지 내렸는지가 아니라, '그 범위 안에서 얼마나 강하게 마감했는지'까지 반영해요. 고가 근처에서 마감하면 매집(+), 저가 근처에서 마감하면 분산(−)으로 봐요.",
    tip: "가격은 신고가를 갱신하는데 AD Line이 안 따라오면, 그 상승에 실제 매수세가 덜 실려있다는 경고 신호로 해석되기도 해요.",
    visual: { type: "pane-line", calc: "adline" },
  },

  // ==================== 기타지표 ====================
  // 아래 항목들은 실제 데이터 피드(개인/기관 수급, 신용거래 등)가 있어야
  // 계산되는 지표라, 우리 캔들 데이터만으로는 값을 만들어낼 수 없어요.
  // 애니메이션은 개념 이해를 돕기 위한 예시(가상 데이터)이고, 실제 값이
  // 아니라는 점을 명확히 밝혀둬요.
  {
    id: "personalNet",
    category: "other",
    name: "개인 순매수",
    eng: "Individual Net Buying",
    summary: "그날 개인 투자자들이 순수하게 얼마나 사고팔았는지(매수 − 매도)를 보여주는 지표",
    detail: "증권거래소가 집계하는 투자자별(개인/외국인/기관) 매매 동향 데이터로 계산돼요. 이 데모의 그래프는 개념 설명용 예시 데이터이며, 실제 수급 데이터가 아니에요.",
    tip: "개인이 순매수하는 날 주가가 오르면, 그 상승이 '누구의 힘'으로 만들어졌는지 함께 살펴보는 용도로 흔히 참고돼요.",
    visual: { type: "pane-line", calc: "synthetic", seed: 2, bias: 0.5 },
  },
  {
    id: "creditRatio",
    category: "other",
    name: "신용잔고율",
    eng: "Margin Balance Ratio",
    summary: "전체 유통주식 수 대비, 빚내서(신용거래로) 산 주식의 비율",
    detail: "증권사에서 돈을 빌려 주식을 산 '신용거래' 잔고가 전체 주식 수 대비 얼마나 되는지 보여줘요. 증권사 자체 데이터가 있어야 계산되는 지표라, 그래프는 예시 데이터예요.",
    tip: "신용잔고율이 지나치게 높으면, 주가가 조금만 하락해도 반대매매(강제 청산)가 쏟아질 위험이 있다는 경고로 흔히 해석돼요.",
    visual: { type: "pane-line", calc: "synthetic", seed: 3.1, bias: 0.3 },
  },
  {
    id: "creditBalance",
    category: "other",
    name: "신용잔고",
    eng: "Margin Balance",
    summary: "신용잔고율의 비율(%) 대신, 실제 주식 수(또는 금액)로 보여주는 지표",
    detail: "신용잔고율과 개념은 같은데, %가 아니라 절대적인 수량·금액으로 표시돼요. 마찬가지로 실제 증권사 데이터가 필요해서 그래프는 예시예요.",
    tip: "신용잔고가 꾸준히 늘어나는 종목은, 그만큼 주가 하락 시 매도 압력(반대매매)이 커질 수 있는 잠재 리스크를 안고 있다고 봐요.",
    visual: { type: "pane-line", calc: "synthetic", seed: 4.2, bias: 0.35 },
  },
  {
    id: "deposit",
    category: "other",
    name: "고객예탁금",
    eng: "Client Deposits",
    summary: "투자자들이 증권 계좌에 넣어두고 아직 안 쓴 대기 자금의 규모",
    detail: "주식을 안 사고 계좌에 현금으로 대기 중인 돈이 얼마나 되는지를 보여줘요. 개별 종목이 아니라 시장 전체의 투자 여력을 가늠하는 데 주로 쓰여요.",
    tip: "고객예탁금이 꾸준히 늘어나면, 시장에 대기 중인 매수 여력이 쌓이고 있다는 긍정적 신호로 흔히 해석돼요.",
    visual: { type: "pane-line", calc: "synthetic", seed: 5.3, bias: 0.2 },
  },
  {
    id: "newsCount",
    category: "other",
    name: "뉴스건수",
    eng: "News Count",
    summary: "그 종목에 대한 뉴스가 하루에 몇 건이나 나왔는지 세어서 보여주는 지표",
    detail: "뉴스매매의 핵심 기능(실시간 뉴스-관련주 매칭)과 가장 밀접한 지표예요. 관심이 몰리는 종목일수록 관련 뉴스 건수도 함께 늘어나는 경향이 있어요.",
    tip: "평소보다 뉴스 건수가 갑자기 급증하는 종목은, 시장의 관심이 쏠리고 있다는 신호로 참고할 수 있어요.",
    visual: { type: "pane-bars" },
  },
  {
    id: "strength",
    category: "other",
    name: "체결강도",
    eng: "Execution Strength",
    summary: "매수 주문과 매도 주문 중 어느 쪽이 더 활발하게 체결되고 있는지를 보여주는 실시간 지표",
    detail: "100을 기준으로, 100보다 높으면 매수 체결이 더 활발하다는 뜻이고 낮으면 매도 체결이 더 활발하다는 뜻이에요. 실시간 호가창 데이터가 있어야 계산되는 지표라 그래프는 예시예요.",
    tip: "체결강도가 급격히 치솟는 순간은, 매수 주문이 몰리면서 단기적으로 힘이 실리고 있다는 신호로 단타 매매에서 자주 참고돼요.",
    visual: { type: "pane-oscillator-center", calc: "momentum" },
  },
  {
    id: "investorType",
    category: "other",
    name: "투자자별 매매동향",
    eng: "Investor Type Flow",
    summary: "개인·외국인·기관 세 그룹이 각각 그날 얼마나 사고팔았는지 나란히 비교하는 지표",
    detail: "누가 사고 누가 팔았는지를 그룹별로 나눠서 보여줘요. 특히 외국인·기관의 매매 방향은 개인 투자자들이 참고 지표로 많이 활용해요.",
    tip: "외국인과 기관이 동시에 순매수하는 종목은, 시장에서 상대적으로 긍정적으로 평가받고 있다는 신호로 흔히 해석돼요.",
    visual: { type: "pane-line", calc: "synthetic", seed: 6.4, bias: 0.55 },
  },
  {
    id: "openInterest",
    category: "other",
    name: "미결제 약정",
    eng: "Open Interest",
    summary: "선물·옵션 시장에서 아직 청산되지 않고 남아있는 계약의 총 수량",
    detail: "개별 주식이 아니라 선물·옵션 파생상품 시장에서 쓰이는 지표예요. 아직 반대매매로 청산되지 않은 계약이 얼마나 쌓여있는지를 보여줘요.",
    tip: "가격이 오르면서 미결제 약정도 같이 늘어나면 그 상승에 새로운 자금이 들어오고 있다는 뜻이라 추세가 견고하다고 흔히 해석해요.",
    visual: { type: "pane-line", calc: "synthetic", seed: 7.5, bias: 0.4 },
  },
  {
    id: "basis",
    category: "other",
    name: "베이시스",
    eng: "Basis",
    summary: "선물 가격이 현물(실제 주가) 가격보다 얼마나 비싸거나 싼지의 차이",
    detail: "이론적으로 선물 가격은 현물보다 약간 비싼 게 정상(콘탱고)인데, 이 차이(베이시스)가 비정상적으로 벌어지거나 역전(백워데이션)되면 시장 심리를 읽는 단서가 돼요.",
    tip: "베이시스가 갑자기 크게 벌어지면, 프로그램 매매(차익거래)가 유입되면서 시장 전체의 수급에 영향을 줄 수 있다고 흔히 해석돼요.",
    visual: { type: "pane-oscillator-center", calc: "roc" },
  },
];
