// 차트 가이드 — 1차 배치 (16개). 스크린샷에 나온 4개 카테고리(차트유형/오버레이/
// 보조지표/기타지표) 체계를 그대로 따라가되, 우선 가장 많이 쓰이고 대표적인
// 지표들부터 채웠다. 나머지는 다음 배치에서 이어서 추가할 예정.

export const CATEGORIES = [
  { id: "chartform", label: "차트유형" },
  { id: "overlay", label: "오버레이" },
  { id: "oscillator", label: "보조지표" },
];

export const INDICATORS = [
  // ---- 차트유형 ----
  {
    id: "candle",
    category: "chartform",
    name: "캔들차트",
    eng: "Candlestick",
    summary: "시가·고가·저가·종가 4가지 가격을 몸통과 꼬리로 표현하는 가장 기본적인 차트",
    detail:
      "몸통은 시가와 종가 사이 구간, 위아래 꼬리는 그날의 고가·저가를 나타내요. 한국 시장에서는 종가가 시가보다 높으면 빨간색(양봉), 낮으면 파란색(음봉)으로 표시해요.",
    tip: "몸통이 길수록 그 기간 동안 힘있게 움직였다는 뜻이고, 꼬리가 길면 한쪽으로 밀렸다가 다시 되돌아왔다는 뜻이에요.",
    visual: { type: "chartform", form: "candle" },
  },
  {
    id: "line",
    category: "chartform",
    name: "라인차트",
    eng: "Line",
    summary: "종가만 이어서 그린 가장 단순한 차트",
    detail: "각 기간의 종가만 점으로 찍고 선으로 연결해요. 세부 변동은 안 보이지만 전체 추세를 한눈에 파악하기 좋아요.",
    tip: "여러 종목의 장기 추세를 겹쳐서 비교할 때 특히 유용해요.",
    visual: { type: "chartform", form: "line" },
  },
  {
    id: "area",
    category: "chartform",
    name: "영역라인",
    eng: "Area",
    summary: "라인차트 아래를 색으로 채워 추세를 더 강조한 형태",
    detail: "기본 구조는 라인차트와 같고, 선 아래 영역을 채색해서 상승·하락의 크기를 시각적으로 더 도드라지게 보여줘요.",
    tip: "여러 종목을 겹쳐 그릴 땐 오히려 라인차트가 더 보기 편할 수 있어요 — 영역라인은 단일 종목 볼 때 강점이 있어요.",
    visual: { type: "chartform", form: "area" },
  },
  {
    id: "bar",
    category: "chartform",
    name: "바차트",
    eng: "OHLC Bar",
    summary: "캔들의 몸통 없이 시가·고가·저가·종가를 선으로만 표시",
    detail: "세로선이 고가~저가 범위, 왼쪽 짧은 가지가 시가, 오른쪽 짧은 가지가 종가예요. 캔들과 정보량은 같지만 더 가늘게 표시돼요.",
    tip: "여러 지표를 겹쳐 볼 때 캔들 몸통이 다른 선을 가리는 게 싫다면 바차트가 더 깔끔해요.",
    visual: { type: "chartform", form: "bar" },
  },
  {
    id: "heikin",
    category: "chartform",
    name: "Heikin-Ashi",
    eng: "Heikin-Ashi",
    summary: "직전 캔들 값을 평균내어 추세를 매끄럽게 보여주는 변형 캔들",
    detail: "일반 캔들과 계산식이 달라서(직전 시가·종가 평균 등) 잔파동이 줄어들고 추세가 지속되는 구간이 색으로 뭉쳐서 보여요.",
    tip: "같은 색 캔들이 연속되면 추세가 강하다는 뜻이고, 몸통이 거의 없는 캔들이 나오면 힘이 빠지고 있다는 신호로 봐요.",
    visual: { type: "chartform", form: "heikin" },
  },

  // ---- 오버레이 ----
  {
    id: "sma",
    category: "overlay",
    name: "이동평균선",
    eng: "Moving Average (MA)",
    summary: "최근 N일 종가의 평균을 이어 그린, 가장 널리 쓰이는 추세선",
    detail: "가격의 잔물결을 지우고 큰 흐름만 보여줘요. 여러 기간(5일선, 20일선, 60일선 등)을 같이 놓고 배열을 보는 게 일반적이에요.",
    tip: "가격이 이동평균선 위에 있으면 상승 추세, 아래 있으면 하락 추세로 해석하는 게 기본이에요.",
    visual: { type: "overlay-line", period: 6 },
  },
  {
    id: "bollinger",
    category: "overlay",
    name: "Bollinger Band",
    eng: "Bollinger Band",
    summary: "이동평균선 위아래로 변동성만큼 밴드를 그린 지표",
    detail: "가격 변동이 커지면 밴드 폭이 넓어지고, 잠잠해지면 좁아져요. 통계적으로 가격은 대부분 이 밴드 안에서 움직여요.",
    tip: "밴드가 좁아졌다가(스퀴즈) 한쪽으로 급하게 벌어지면, 큰 방향성 움직임이 막 시작됐다는 신호로 자주 해석돼요.",
    visual: { type: "overlay-band" },
  },
  {
    id: "ichimoku",
    category: "overlay",
    name: "일목균형표",
    eng: "Ichimoku Cloud",
    summary: "여러 개의 평균선으로 구름(지지·저항대)을 만들어 추세와 균형을 함께 보는 지표",
    detail: "일본에서 개발된 지표로, 여러 선이 겹쳐서 만드는 구름대가 지지선·저항선 역할을 해요. 여기선 핵심 두 선만 단순화해서 보여드려요.",
    tip: "가격이 구름 위에 있으면 상승 우위, 구름 아래 있으면 하락 우위로 해석하는 게 기본 틀이에요.",
    visual: { type: "overlay-cloud" },
  },
  {
    id: "sar",
    category: "overlay",
    name: "Parabolic SAR",
    eng: "Parabolic SAR",
    summary: "가격 위아래로 점을 찍어 추세 전환 시점을 표시하는 지표",
    detail: "점이 가격 아래 있으면 상승 추세, 위로 '점프'해서 옮겨가면 하락 추세로 전환됐다는 신호예요.",
    tip: "점이 자주 뒤집히면(휩소) 추세가 뚜렷하지 않은 횡보장이라는 뜻이니 주의가 필요해요.",
    visual: { type: "overlay-dots" },
  },
  {
    id: "demand-zone",
    category: "overlay",
    name: "매물대",
    eng: "Volume Profile / Demand Zone",
    summary: "특정 가격대에서 얼마나 많은 거래가 쌓였는지 옆으로 표시하는 지표",
    detail: "거래가 많이 몰렸던 가격대는 그만큼 많은 사람이 사고판 '기억'이 남아있는 구간이라, 나중에 그 가격에 다시 오면 지지·저항으로 작용하는 경우가 많아요.",
    tip: "매물대가 두꺼운 구간을 뚫고 올라가면 그 위는 저항이 약해졌다고 보고, 반대로 못 뚫으면 저항대로 작용했다고 해석해요.",
    visual: { type: "overlay-zone" },
  },

  // ---- 보조지표 ----
  {
    id: "volume",
    category: "oscillator",
    name: "거래량",
    eng: "Volume",
    summary: "그 기간 동안 실제로 얼마나 많은 주식이 거래됐는지 보여주는 막대그래프",
    detail: "가격 아래에 막대로 표시되며, 캔들 색과 맞춰서 상승일엔 빨간, 하락일엔 파란 막대로 표시되는 경우가 많아요.",
    tip: "가격이 크게 움직였는데 거래량이 평소보다 훨씬 많다면, 그 움직임의 신뢰도가 더 높다고 보는 게 일반적이에요.",
    visual: { type: "pane-bars" },
  },
  {
    id: "rsi",
    category: "oscillator",
    name: "RSI",
    eng: "Relative Strength Index",
    summary: "최근 상승폭과 하락폭의 비율로 과열·침체 정도를 0~100 사이 숫자로 보여주는 지표",
    detail: "70 이상이면 과매수(너무 많이 올랐다), 30 이하면 과매도(너무 많이 빠졌다) 구간으로 흔히 해석해요.",
    tip: "가격은 신고가를 갱신하는데 RSI는 그만큼 안 오르는 '다이버전스'가 나오면, 추세 전환의 초기 신호로 자주 언급돼요.",
    visual: { type: "pane-oscillator", calc: "rsi", bands: [30, 70] },
  },
  {
    id: "stochastic",
    category: "oscillator",
    name: "스토캐스틱",
    eng: "Stochastic",
    summary: "최근 일정 기간의 고가·저가 범위 안에서 현재 가격의 위치를 0~100으로 표시",
    detail: "80 이상은 그 기간 범위의 최상단 근처(과매수), 20 이하는 최하단 근처(과매도)로 흔히 해석해요.",
    tip: "RSI보다 반응이 더 빨라서(민감해서) 짧은 구간 매매 참고용으로 많이 쓰이지만, 그만큼 신호도 자주 나와요.",
    visual: { type: "pane-oscillator", calc: "stochastic", bands: [20, 80] },
  },
  {
    id: "macd",
    category: "oscillator",
    name: "MACD",
    eng: "Moving Average Convergence Divergence",
    summary: "단기·장기 이동평균선의 차이를 이용해 추세의 방향과 힘을 보는 지표",
    detail: "MACD선(주황)이 시그널선(파랑)을 위로 뚫으면 매수 신호, 아래로 뚫으면 매도 신호로 흔히 해석해요. 막대(히스토그램)는 두 선의 차이 크기예요.",
    tip: "히스토그램 막대가 점점 짧아지고 있다면, 지금 추세의 힘이 빠지고 있다는 신호로 종종 해석돼요.",
    visual: { type: "pane-macd" },
  },
  {
    id: "obv",
    category: "oscillator",
    name: "OBV",
    eng: "On Balance Volume",
    summary: "가격이 오른 날엔 거래량을 더하고 내린 날엔 빼서, 거래량의 누적 흐름을 선으로 표시",
    detail: "가격보다 거래량(수급)의 큰 흐름을 먼저 보여주는 지표예요. 가격은 아직 안 움직였는데 OBV가 먼저 방향을 잡는 경우가 있어요.",
    tip: "가격은 옆으로 횡보하는데 OBV가 꾸준히 오른다면, 조용히 매집이 진행되고 있다는 신호로 해석되기도 해요.",
    visual: { type: "pane-line", calc: "obv" },
  },
  {
    id: "disparity",
    category: "oscillator",
    name: "이격도",
    eng: "Disparity",
    summary: "현재 가격이 이동평균선에서 몇 % 떨어져 있는지 보여주는 지표",
    detail: "100이면 가격이 이동평균선과 정확히 같다는 뜻이에요. 100보다 많이 높으면 평균보다 너무 많이 올랐다는 뜻이고, 많이 낮으면 너무 많이 빠졌다는 뜻이에요.",
    tip: "이격도가 극단적으로 벌어지면, 평균 쪽으로 되돌아오려는 힘(평균 회귀)이 작용할 가능성이 있다고 보는 시각이 있어요.",
    visual: { type: "pane-oscillator-center" },
  },
];
